=== nmo0/Automata.MiniORM/Automata.MiniORM.Xml.Test/Xml/DTD/SqlMapper.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="mapper" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="if" nillable="true">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="test" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="trim" nillable="true">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="prefix" type="xs:string" />
      <xs:attribute name="prefixOverrides" type="xs:string" />
      <xs:attribute name="suffix" type="xs:string" />
      <xs:attribute name="suffixOverrides" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="foreach" nillable="true">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="collection" type="xs:string" />
      <xs:attribute name="item" type="xs:string" />
      <xs:attribute name="index" type="xs:string" />
      <xs:attribute name="open" type="xs:string" />
      <xs:attribute name="close" type="xs:string" />
      <xs:attribute name="separator" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="mapper">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="if" />
        <xs:element ref="trim" />
        <xs:element name="select">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="trim" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="foreach" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="update">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="trim" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="foreach" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="delete">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="trim" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="foreach" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="insert">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="trim" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="foreach" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="other">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="trim" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="foreach" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nmo0/Automata.MiniORM/Automata.MiniORM.Xml.Test/Xml/DotSample/DataBase.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapper xsi:noNamespaceSchemaLocation="../DTD/SqlMapper.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <other id="sys_drop_table" parameterType="string">
    drop table dbo.#{args}
  </other>
  <other id="sys_truncate_table" parameterType="string">
    truncate table dbo.#{args}
  </other>
  <other id="sys_create_table" parameterType="Automata.MiniORM.Xml.CreateTableInfo">
    if object_id(N'#{args.TableName}',N'U') is null begin create table dbo.#{args.TableName}
    <foreach collection="args.Columns" index="i" item="item" open="(" close=")" separator=",">
      #{item.Name}
      <if test="item.Type == &quot;String&quot; &amp;&amp; item.Length > -1">
        nvarchar(#{item.Length})
      </if>
      <if test="item.Type == &quot;String&quot; &amp;&amp; item.Length == -1">
        nvarchar(max)
      </if>
      <if test="item.Type == &quot;Int32&quot;">
        int
      </if>
      <if test="item.Type == &quot;Decimal&quot; || item.Type == &quot;Single&quot; || item.Type == &quot;Double&quot;">
        decimal(#{item.Length}, #{item.Accuracy})
      </if>
      <if test="item.Type == &quot;DateTime&quot;">
        datetime
      </if>
      <if test="item.Type == &quot;Boolean&quot;">
        bit
      </if>
      <if test="item.Attributes.Contains(&quot;KeyAttribute&quot;)">
        primary key
      </if>
      <if test="item.Attributes.Contains(&quot;SinceTheIncreaseAttribute&quot;)">
        primary key identity(1, 1)
      </if>
    </foreach>
    end
  </other>
</mapper>

=== nmo0/Automata.MiniORM/Automata.MiniORM.Xml/Xml/Sample/DataBase.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapper xsi:noNamespaceSchemaLocation="../DTD/SqlMapper.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <other id="sys_drop_table">
    drop table dbo.#{args}
  </other>
  <other id="sys_truncate_table">
    truncate table dbo.#{args}
  </other>
  <other id="sys_create_table">
    if object_id(N'#{args.TableName}',N'U') is null begin create table dbo.#{args.TableName}
    <foreach collection="args.Columns" index="i" item="item" open="(" close=")" separator=",">
      #{item.Name}
      <if test="item.Type === 'String' &amp;&amp; item.Length > -1">
        nvarchar(#{item.Length})
      </if>
      <if test="item.Type === 'String' &amp;&amp; item.Length === -1">
        nvarchar(max)
      </if>
      <if test="item.Type === 'Int32'">
        int
      </if>
      <if test="item.Type === 'Decimal' || item.Type === 'Single' || item.Type === 'Double'">
        decimal(#{item.Length}, #{item.Accuracy})
      </if>
      <if test="item.Type === 'DateTime'">
        datetime
      </if>
      <if test="item.Type === 'Boolean'">
        bit
      </if>
      <if test="item.Attributes.indexOf('KeyAttribute') > -1">
        primary key
      </if>
      <if test="item.Attributes.indexOf('SinceTheIncreaseAttribute') > -1">
        primary key identity(1, 1)
      </if>
    </foreach>
    end
  </other>
</mapper>
