=== nmo0/Automata.MiniORM/Automata.MiniORM.Xml/Xml/DTD/SqlMapper.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="mapper" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="if" nillable="true">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="test" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="mapper">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="if" />
        <xs:element name="select">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="update">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="delete">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="insert">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element ref="if" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="parameterType" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nmo0/Automata.MiniORM/Automata.MiniORM.Xml/Xml/Sample/MySqlMapper.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapper xsi:noNamespaceSchemaLocation="../DTD/SqlMapper.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <select id="testsql" parameterType="object">
    testtest
    asdfe
  </select>
  <update id="testsql" parameterType="object">
    testtest
    <if test="a == '123'">
      test23423 ${a}
    </if>
    <if test="a == '234'">
      test23423
    </if>
    asdfe
  </update>
  <delete id="testsql" parameterType="object">
    testtest
    <if test="a == '123'">
      test23423 ${a}
    </if>
    <if test="a == '234'">
      test23423
    </if>
    asdfe
  </delete>
  <insert id="testsql" parameterType="object">
    testtest
    <if test="a == '123'">
      test23423 ${a}
    </if>
    <if test="a == '234'">
      test23423
    </if>
    asdfe
  </insert>
</mapper>
